### ISSUE TITLE
GRIB files output switched from Kelvin to Celsius starting on run 2024-04-17 0z

### ISSUE THREAD

**Issue by patrick-zippenfenig** [NOAA-EMC/graphcast#39] opened 2024-04-19 08:35 UTC
GRIB files on AWS switched from Kelvin to Celsius on run 2024-04-17 0z and current runs after 2024-04-18 12z. Record `parameterUnits` shows Kelvin, but Celsius is stored. Effects 2m and pressure level temperature.

![Screenshot 2024-04-19 at 10 09 31](https://github.com/NOAA-EMC/graphcast/assets/11670456/2510d168-24ef-4225-a53f-82102a361d2f)

Originally reported by @bzigterman in https://github.com/open-meteo/open-meteo/issues/748

**Comment by patrick-zippenfenig** [comment] 2024-04-19 10:58
I applied a simple correction by -273.15. For most locations this corrects the issue. However, some locations show unreasonable differences of 15K compared to GFS. I suspect that issue could already be present in the initialisation data for GFS GraphCast. 

![Screenshot 2024-04-19 at 12 55 33](https://github.com/NOAA-EMC/graphcast/assets/11670456/d53bd4f8-d4d2-4c83-82fe-adc7daf134f9)

You can try it here: https://open-meteo.com/en/docs#latitude=40.1106&longitude=-88.2073&current=&hourly=temperature_2m,temperature_500hPa&past_days=5&models=gfs_global,gfs_graphcast025

**Comment by SadeghTabas-NOAA** [comment] 2024-04-25 06:49
@patrick-zippenfenig I was wondering if the issue is with either 13PL or 37PL forecasts? Also, I wanted to let you know that we will soon shift to GraphCastGFS V2 which will have a higher accuracy for 13PLs. Thanks

**Comment by patrick-zippenfenig** [comment] 2024-04-25 06:59
I am using 37PL. Will you only use the new weights for 13PL?

**Comment by SadeghTabas-NOAA** [comment] 2024-04-25 07:02
@patrick-zippenfenig Yes, at this time we only focused on 13PL, we might stop providing forecasts for 37PL in a couple of days. Please let me know if you can see the same issue with 13PL as well, so I can work on it. Also, I wanted to note that the 13PL forecasts are more accurate compared to 37PL in the current version.

**Comment by patrick-zippenfenig** [comment] 2024-04-25 07:05
Oh, that's good to know. I will switch to 13PL and disable the automatic kelvin/celsius detection to see if there are any issues

**Comment by SadeghTabas-NOAA** [comment] 2024-04-25 07:06
Thank you so much

**Comment by SadeghTabas-NOAA** [comment] 2024-04-25 16:41
@patrick-zippenfenig I'm checking the 37PL forecasts for 2024-04-17 0z and I dont see the issue for 2mt variable, I checked *.006 and *.036 files. Could you please let me know which file has the issue? Thanks

**Comment by patrick-zippenfenig** [comment] 2024-04-26 10:01
Oh sorry, I believe it is the 37PL `2024-04-17 12z` run. I am using the ECMWF eccodes library to read GRIB2 files. I hope it is easily reproducible and not dependant on some library/environment combination

**Comment by SadeghTabas-NOAA** [comment] 2024-04-26 15:03
@patrick-zippenfenig Thanks for providing this. The corrected forecasts would be available in 2 or 3 hours. The model ICs were corrupted for those dates which resulted issues in all variables including TMP. Thanks

**Comment by SadeghTabas-NOAA** [comment] 2024-04-26 16:40
As I fixed the forecasts, I close this issue.

**Comment by patrick-zippenfenig** [comment] 2024-04-26 16:41
Thank you!

**Closed by SadeghTabas-NOAA** 2024-04-26 16:40 UTC
Labels: bug
